// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCulcJfSrpX9875wXS4zhvGt2BeoEmBK_g',
    appId: '1:1086608418210:web:671fc274568bf2f2f17efb',
    messagingSenderId: '1086608418210',
    projectId: 'moviee-3dd16',
    authDomain: 'moviee-3dd16.firebaseapp.com',
    storageBucket: 'moviee-3dd16.appspot.com',
    measurementId: 'G-9CSKNTYP26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Nd4pxcG4lltICaO4RWiYC0M45quICDQ',
    appId: '1:1086608418210:android:eb7945e0863b5e5af17efb',
    messagingSenderId: '1086608418210',
    projectId: 'moviee-3dd16',
    storageBucket: 'moviee-3dd16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH_EIDE5ziZfhlhzLcsodWcmWeasmpTc8',
    appId: '1:1086608418210:ios:e6c03d2c3b01c588f17efb',
    messagingSenderId: '1086608418210',
    projectId: 'moviee-3dd16',
    storageBucket: 'moviee-3dd16.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH_EIDE5ziZfhlhzLcsodWcmWeasmpTc8',
    appId: '1:1086608418210:ios:e6c03d2c3b01c588f17efb',
    messagingSenderId: '1086608418210',
    projectId: 'moviee-3dd16',
    storageBucket: 'moviee-3dd16.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCulcJfSrpX9875wXS4zhvGt2BeoEmBK_g',
    appId: '1:1086608418210:web:bd25f3163ba425e4f17efb',
    messagingSenderId: '1086608418210',
    projectId: 'moviee-3dd16',
    authDomain: 'moviee-3dd16.firebaseapp.com',
    storageBucket: 'moviee-3dd16.appspot.com',
    measurementId: 'G-3H5DB5MR2C',
  );
}
